os:
  - linux
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libsqlite3-mod-spatialite; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libspatialite; fi
